/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 palhero-parts.glb --types
Source: public/models/palhero-parts.glb (Draco-compressed, parts preserved)

15 unique meshes + 4 instanced groups. Each <mesh> below is an individually
controllable element — give it a ref, change position/rotation/scale/visible,
or swap its material.

GRID_SQUARE_SIZE 

*/

"use client";

import * as THREE from "three";
import { useMemo, useRef } from "react";
import { useFrame, type ThreeEvent } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh1010: THREE.Mesh;
    Mesh1002: THREE.Mesh;
    Mesh1033: THREE.Mesh;
    Mesh1066: THREE.Mesh;
    Mesh1081: THREE.Mesh;
    Mesh1037: THREE.Mesh;
    Mesh1034: THREE.Mesh;
    Mesh1067: THREE.Mesh;
    Mesh1082: THREE.Mesh;
    Mesh1084: THREE.Mesh;
    Mesh1071: THREE.Mesh;
    Mesh1073: THREE.Mesh;
    Mesh1079: THREE.Mesh;
    Mesh1080: THREE.Mesh;
    Mesh10: THREE.Mesh;
    Mesh1063: THREE.InstancedMesh;
    Mesh1045: THREE.InstancedMesh;
    Mesh1059: THREE.InstancedMesh;
    Mesh1034_1: THREE.InstancedMesh;
  };
  materials: Record<string, never>;
};

// Street transform — shared by the road mesh and the lane-marking geometry so
// the white lines line up exactly on top of the road.
// X scale = how LONG the road is. The mesh's local X extent is 1.906066, so the
// road's world length = STREET_SCALE.x * 1.906066. Here it's stretched to fill the
// WHOLE ground end-to-end (≈ 335 units, world X ∈ [-217, +118]) and re-centred on
// the ground's centre (X = -49.449) so both ends reach the ground edges. The
// Bridge's DECK_LENGTH + X are kept matched to this — see Bridge.tsx / animate.tsx.
const STREET_POSITION: [number, number, number] = [-49.449, 0.08, 0];
const STREET_SCALE: [number, number, number] = [527.436, 1.8, 3.62]; // X (length) = 3× the original 175.812

// Ground transform — shared by the ground mesh and the grid overlay so the grid
// is measured and placed against the ground's real surface.
const GROUND_POSITION: [number, number, number] = [-49.794, 0, 0];
const GROUND_SCALE: [number, number, number] = [528.522, 0.1, 149.787]; // X (length) = 3× the original 176.174

// ─── Room enclosure (4 walls + a ceiling wrapped around the ground) ───────────
// Built from the ground's measured extent (see buildGround), so the four walls
// stand exactly on the ground's edges, rise to ROOM_HEIGHT, and a flat ceiling
// caps the top. Drawn as thin solid boxes (not planes) so they read as real
// surfaces from any angle and take light / shadow like the rest of the scene.
const ROOM_HEIGHT = 32; // wall height above the ground surface (world units)
const ROOM_THICKNESS = 0.5; // wall / ceiling thickness
const ROOM_COLOR = "#E9E8E3"; // wall + ceiling colour (matches the page paper)
const ROOM_ROUGHNESS = 0.95; // 1 = fully matte; lower adds a faint sheen

// ─── Ground grid overlay (the "ShapeGrid" square animation, drawn in 3D) ──────
// A flat plane laid on the ground, painted by a shader with light-grey square
// borders and a blue fill on the cell under the cursor — the 3D equivalent of
// <ShapeGrid squareSize=45 borderColor="#e3e3e3" hoverFillColor="#3B82F6" />.
const GRID_SQUARE_SIZE = 0.7; // world units per cell (≈ ShapeGrid squareSize)
const GRID_BORDER_COLOR = "#C7C7C7"; // square OUTLINE colour (the grid lines)
const GRID_FILL_COLOR = "#E4E4E4"; // square INTERIOR colour, BEFORE hover — change this
const GRID_FILL_OPACITY = 0.71; // resting fill strength (0 = fully transparent squares)
const GRID_HOVER_COLOR = "#7096FE"; // fill of the hovered cell
const GRID_LINE_WIDTH = 0.001; // border thickness in world units
const GRID_OPACITY = 0.9; // overall line opacity (lets the ground show through)
const GRID_HOVER_OPACITY = 0.85; // opacity of the blue hover fill
const GRID_SPEED = 0; // cells/sec scroll — 0 = static, like ShapeGrid speed={0}
const GRID_DIRECTION: [number, number] = [1, 1]; // scroll vector (diagonal)
const GRID_HOVER_TRAIL = 0; // extra cells lit around the hovered one (0 = single)

// Turn a "#rrggbb" string into a raw sRGB vec3. The grid uses a plain
// ShaderMaterial (no colour-management chunks), so its output is written to the
// screen as-is — feeding it the un-linearised sRGB values keeps the colours
// matching the CSS hex exactly.
function hexToRGB(hex: string): THREE.Vector3 {
  const n = parseInt(hex.replace("#", ""), 16);
  return new THREE.Vector3(
    ((n >> 16) & 255) / 255,
    ((n >> 8) & 255) / 255,
    (n & 255) / 255
  );
}

// Measure the ground's real world extent from its geometry (the mesh has no
// rotation, so world extent = position + scale * local bounding box) and return
// where to place / how big to make the flat grid plane that sits on top of it.
function buildGround(geometry: THREE.BufferGeometry) {
  geometry.computeBoundingBox();
  const bb = geometry.boundingBox!;
  const [px, py, pz] = GROUND_POSITION;
  const [sx, sy, sz] = GROUND_SCALE;
  const minX = px + sx * bb.min.x;
  const maxX = px + sx * bb.max.x;
  const minZ = pz + sz * bb.min.z;
  const maxZ = pz + sz * bb.max.z;
  return {
    centerX: (minX + maxX) / 2,
    centerZ: (minZ + maxZ) / 2,
    width: maxX - minX,
    depth: maxZ - minZ,
    topY: py + sy * bb.max.y, // the ground's upper face
  };
}

const GRID_VERTEX_SHADER = /* glsl */ `
  #include <fog_pars_vertex>
  varying vec2 vUv;
  void main() {
    vUv = uv;
    vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);
    gl_Position = projectionMatrix * mvPosition;
    #include <fog_vertex>
  }
`;

const GRID_FRAGMENT_SHADER = /* glsl */ `
  #include <fog_pars_fragment>

  uniform float uTime;
  uniform float uSpeed;
  uniform float uSquareSize;
  uniform float uLineWidth;
  uniform float uOpacity;
  uniform float uFillOpacity;
  uniform float uHoverOpacity;
  uniform float uHoverTrail;
  uniform vec2  uPlaneSize;
  uniform vec2  uDir;
  uniform vec2  uHover;
  uniform vec3  uBorderColor;
  uniform vec3  uFillColor;
  uniform vec3  uHoverColor;

  varying vec2 vUv;

  void main() {
    // Grid coordinates measured in whole cells; scroll over time for the
    // diagonal animation (uSpeed = 0 → a static grid, like ShapeGrid speed={0}).
    vec2 cells  = (vUv * uPlaneSize) / uSquareSize + uDir * uTime * uSpeed;
    vec2 cellId = floor(cells);
    vec2 f      = fract(cells);

    // Anti-aliased border: distance (in cell units) to the nearest cell edge.
    vec2 distEdge = min(f, 1.0 - f);
    float d  = min(distEdge.x, distEdge.y);
    float t  = uLineWidth / uSquareSize;   // line half-width as a fraction of a cell
    float aa = fwidth(d);
    float line = 1.0 - smoothstep(t - aa, t + aa, d);

    // Hover fill — a square (Chebyshev) block of cells around the hovered one.
    float hover = 0.0;
    if (uHover.x > -0.5) {
      vec2 hd = abs(cellId - uHover);
      float cheb = max(hd.x, hd.y);
      hover = 1.0 - step(uHoverTrail + 0.5, cheb);
    }

    // Compose: resting square fill → hover fill on the hovered block → grey
    // border lines on top of everything.
    vec3  color = uFillColor;
    float alpha = uFillOpacity;
    color = mix(color, uHoverColor, hover);
    alpha = max(alpha, hover * uHoverOpacity);
    color = mix(color, uBorderColor, line);
    alpha = max(alpha, line * uOpacity);

    if (alpha < 0.001) discard;

    gl_FragColor = vec4(color, alpha);
    #include <fog_fragment>
  }
`;

/*
Builds the cartoon street surface on the client:
 • a procedurally-drawn dark asphalt texture, and
 • a 4-step toon gradient so the toon material shades in crisp cel bands.
The white lane lines are NOT drawn here — the road model has no usable UVs, so
painted-on markings never show. They're added as real geometry instead (see
buildStreetLines). Drawn to a <canvas>, so this only runs in the browser.
*/
function createStreetTextures() {
  // ── dark cartoon asphalt ──────────────────────────────────────────────────
  const road = document.createElement("canvas");
  road.width = 256;
  road.height = 128;
  const r = road.getContext("2d")!;

  // flat cartoon asphalt (lighter blue-grey to sit with the scene palette)
  r.fillStyle = "#686868";
  r.fillRect(0, 0, 200, 128);

  // a few faint lighter patches so it isn't dead flat — kept subtle to stay "drawn"
  r.fillStyle = "rgba(255, 255, 255, 0.04)";
  for (const [x, y, rad] of [
    [40, 30, 26],
    [150, 92, 34],
    [212, 40, 20],
    [92, 104, 18],
  ] as const) {
    r.beginPath();
    r.arc(x, y, rad, 0, Math.PI * 2);
    r.fill();
  }

  const roadMap = new THREE.CanvasTexture(road);
  roadMap.colorSpace = THREE.SRGBColorSpace;
  roadMap.wrapS = THREE.RepeatWrapping;
  roadMap.wrapT = THREE.RepeatWrapping;
  roadMap.repeat.set(36, 1);
  roadMap.anisotropy = 8;

  // ── 4-step toon gradient → crisp cel-shaded banding instead of smooth shading ─
  const grad = document.createElement("canvas");
  grad.width = 4;
  grad.height = 1;
  const g = grad.getContext("2d")!;
  ["#9aa1ad", "#bcc2cc", "#dde1e8", "#ffffff"].forEach((stop, i) => {
    g.fillStyle = stop;
    g.fillRect(i, 0, 1, 1);
  });
  const toonGradient = new THREE.CanvasTexture(grad);
  toonGradient.minFilter = THREE.NearestFilter;
  toonGradient.magFilter = THREE.NearestFilter;
  toonGradient.generateMipmaps = false;

  return { roadMap, toonGradient };
}

/*
Works out where to lay the white lane lines. The road model has no usable UVs,
so instead of painting lines into the texture we measure the road's actual
bounding box and return ready-to-place positions/sizes for real line geometry
that sits just on top of the road surface.
*/
function buildStreetLines(geometry: THREE.BufferGeometry) {
  geometry.computeBoundingBox();
  const bb = geometry.boundingBox!;
  const [px, py, pz] = STREET_POSITION;
  const [sx, sy, sz] = STREET_SCALE;

  // mesh has no rotation, so world extent = position + scale * local extent
  const minX = px + sx * bb.min.x;
  const maxX = px + sx * bb.max.x;
  const minZ = pz + sz * bb.min.z;
  const maxZ = pz + sz * bb.max.z;

  const lengthX = maxX - minX;
  const widthZ = maxZ - minZ;
  const centerX = (minX + maxX) / 2;
  const centerZ = (minZ + maxZ) / 2;

  // dashed centre line — evenly spaced dash centres along the road
  const dashCount = 390; // more dashes → closer together (scaled with the 3× longer road)
  const span = lengthX * 0.96;
  const step = span / dashCount;
  const dashes: number[] = [];
  for (let i = 0; i < dashCount; i++) {
    dashes.push(centerX - span / 2 + step * (i + 0.5));
  }

  return {
    y: py + sy * bb.max.y + 0.01, // sit flush, just above the road's top face
    centerX,
    centerZ,
    lengthX,
    stripeW: Math.max(widthZ * 0.035, 0.04), // painted-stripe width (in Z)
    edgeZ: widthZ * 0.42, // how far the edge lines sit from centre
    dashLen: step * 0.3, // short dashes
    dashes,
  };
}

export function Model(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/models/palhero-parts.glb"
  ) as unknown as GLTFResult;

  // Cartoon street surface — built once, on the client.
  const { roadMap, toonGradient } = useMemo(() => createStreetTextures(), []);
  // Where to place the white lane lines (measured from the road's geometry).
  const lines = useMemo(
    () => buildStreetLines(nodes.Mesh1002.geometry),
    [nodes]
  );
  // Flat white "paint" shared by every stripe. polygonOffset keeps it glued to
  // the road surface without z-fighting; no height + no shadow = looks painted.
  const lineMat = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: "#f4f7fb",
        roughness: 0.85,
        emissive: new THREE.Color("#e8eef6"),
        emissiveIntensity: 0.1,
        side: THREE.DoubleSide,
        polygonOffset: true,
        polygonOffsetFactor: -2,
        polygonOffsetUnits: -2,
      }),
    []
  );

  // ── Animated square grid laid flat on the ground (see GRID_* constants) ─────
  const ground = useMemo(() => buildGround(nodes.Mesh1010.geometry), [nodes]);

  // Shared matte material for the four walls + ceiling. DoubleSide so the
  // interior faces show with the camera sitting inside the enclosure.
  const roomMat = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: ROOM_COLOR,
        roughness: ROOM_ROUGHNESS,
        metalness: 0,
        side: THREE.DoubleSide,
      }),
    []
  );
  const gridMat = useRef<THREE.ShaderMaterial>(null);
  const gridUniforms = useMemo(
    () =>
      THREE.UniformsUtils.merge([
        THREE.UniformsLib.fog, // so distant grid lines melt into the scene fog
        {
          uTime: { value: 0 },
          uSpeed: { value: GRID_SPEED },
          uDir: {
            value: new THREE.Vector2(
              GRID_DIRECTION[0],
              GRID_DIRECTION[1]
            ).normalize(),
          },
          uPlaneSize: { value: new THREE.Vector2(ground.width, ground.depth) },
          uSquareSize: { value: GRID_SQUARE_SIZE },
          uLineWidth: { value: GRID_LINE_WIDTH },
          uOpacity: { value: GRID_OPACITY },
          uHoverOpacity: { value: GRID_HOVER_OPACITY },
          uHoverTrail: { value: GRID_HOVER_TRAIL },
          uHover: { value: new THREE.Vector2(-1, -1) },
          uBorderColor: { value: hexToRGB(GRID_BORDER_COLOR) },
          uFillColor: { value: hexToRGB(GRID_FILL_COLOR) },
          uFillOpacity: { value: GRID_FILL_OPACITY },
          uHoverColor: { value: hexToRGB(GRID_HOVER_COLOR) },
        },
      ]),
    [ground.width, ground.depth]
  );

  // Scroll the grid over time — only when it's actually animating.
  useFrame((_, delta) => {
    if (GRID_SPEED !== 0 && gridMat.current) {
      gridMat.current.uniforms.uTime.value += delta;
    }
  });

  // Light up the cell under the cursor. e.uv is the plane's 0..1 UV, so the
  // cell index here is computed exactly the way the shader does it.
  const onGridMove = (e: ThreeEvent<PointerEvent>) => {
    if (!e.uv || !gridMat.current) return;
    e.stopPropagation();
    const cx = Math.floor((e.uv.x * ground.width) / GRID_SQUARE_SIZE);
    const cy = Math.floor((e.uv.y * ground.depth) / GRID_SQUARE_SIZE);
    (gridMat.current.uniforms.uHover.value as THREE.Vector2).set(cx, cy);
  };
  const clearGridHover = () => {
    if (gridMat.current) {
      (gridMat.current.uniforms.uHover.value as THREE.Vector2).set(-1, -1);
    }
  };

  return (
    <group {...props} dispose={null}>
      {/* Ground plane */}
      <mesh castShadow receiveShadow geometry={nodes.Mesh1010.geometry} material={nodes.Mesh1010.material} position={GROUND_POSITION} scale={GROUND_SCALE} />
      {/* Room enclosure — four walls hugging the ground's edges plus a flat
          ceiling on top, all measured from the ground (see ROOM_* constants) so
          they line up exactly with its surface. The ceiling never casts a shadow
          so it can't darken the scene below it. */}
      <group>
        {/* back / front walls — span X, stand at the far / near Z edges */}
        <mesh
          castShadow
          receiveShadow
          material={roomMat}
          position={[ground.centerX, ground.topY + ROOM_HEIGHT / 2, ground.centerZ + ground.depth / 2]}
        >
          <boxGeometry args={[ground.width + ROOM_THICKNESS * 2, ROOM_HEIGHT, ROOM_THICKNESS]} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          material={roomMat}
          position={[ground.centerX, ground.topY + ROOM_HEIGHT / 2, ground.centerZ - ground.depth / 2]}
        >
          <boxGeometry args={[ground.width + ROOM_THICKNESS * 2, ROOM_HEIGHT, ROOM_THICKNESS]} />
        </mesh>
        {/* left / right walls — span Z, stand at the min / max X edges */}
        <mesh
          castShadow
          receiveShadow
          material={roomMat}
          position={[ground.centerX + ground.width / 2, ground.topY + ROOM_HEIGHT / 2, ground.centerZ]}
        >
          <boxGeometry args={[ROOM_THICKNESS, ROOM_HEIGHT, ground.depth]} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          material={roomMat}
          position={[ground.centerX - ground.width / 2, ground.topY + ROOM_HEIGHT / 2, ground.centerZ]}
        >
          <boxGeometry args={[ROOM_THICKNESS, ROOM_HEIGHT, ground.depth]} />
        </mesh>
        {/* ceiling — flat slab capping the top of the walls */}
        <mesh
          receiveShadow
          material={roomMat}
          position={[ground.centerX, ground.topY + ROOM_HEIGHT, ground.centerZ]}
        >
          <boxGeometry args={[ground.width + ROOM_THICKNESS * 2, ROOM_THICKNESS, ground.depth + ROOM_THICKNESS * 2]} />
        </mesh>
      </group>
      {/* Animated square grid — a flat plane lying flush on the ground, painted
          by a shader (light-grey square outlines + a blue fill on the hovered
          cell). The 3D take on the reference <ShapeGrid /> overlay. */}
      <mesh
        rotation={[-Math.PI / 2, 0, 0]}
        position={[ground.centerX, ground.topY + 0.02, ground.centerZ]}
        onPointerMove={onGridMove}
        onPointerOut={clearGridHover}
      >
        <planeGeometry args={[ground.width, ground.depth]} />
        <shaderMaterial
          ref={gridMat}
          fog
          transparent
          depthWrite={false}
          uniforms={gridUniforms}
          vertexShader={GRID_VERTEX_SHADER}
          fragmentShader={GRID_FRAGMENT_SHADER}
        />
      </mesh>
      {/* Street — thicker dark slab with a cartoon asphalt texture */}
      <mesh castShadow receiveShadow geometry={nodes.Mesh1002.geometry} position={STREET_POSITION} scale={STREET_SCALE}>
        <meshToonMaterial map={roadMap} gradientMap={toonGradient} />
      </mesh>
      {/* White lane markings — flat planes lying flush on the road surface, so
          they read as paint (not raised 3D bars) regardless of the road's UVs */}
      <group>
        {/* solid edge lines down both sides */}
        <mesh rotation={[-Math.PI / 2, 0, 0]} position={[lines.centerX, lines.y, lines.centerZ + lines.edgeZ]} material={lineMat}>
          <planeGeometry args={[lines.lengthX * 0.98, lines.stripeW]} />
        </mesh>
        <mesh rotation={[-Math.PI / 2, 0, 0]} position={[lines.centerX, lines.y, lines.centerZ - lines.edgeZ]} material={lineMat}>
          <planeGeometry args={[lines.lengthX * 0.98, lines.stripeW]} />
        </mesh>
        {/* dashed centre line */}
        {lines.dashes.map((x, i) => (
          <mesh key={i} rotation={[-Math.PI / 2, 0, 0]} position={[x, lines.y, lines.centerZ]} material={lineMat}>
            <planeGeometry args={[lines.dashLen, lines.stripeW]} />
          </mesh>
        ))}
      </group>
      {/* Buildings (4 in a row) */}
      <mesh castShadow receiveShadow geometry={nodes.Mesh1033.geometry} material={nodes.Mesh1033.material} position={[-3.455, 1.318, -20.257]} rotation={[-Math.PI, 0.006, -Math.PI]} scale={3} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh1066.geometry} material={nodes.Mesh1066.material} position={[-37.234, 1.318, -20.257]} rotation={[-Math.PI, 0.006, -Math.PI]} scale={3} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh1081.geometry} material={nodes.Mesh1081.material} position={[-74.667, 1.318, -20.257]} rotation={[-Math.PI, 0.006, -Math.PI]} scale={3} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh1037.geometry} material={nodes.Mesh1037.material} position={[-109.414, 1.318, -20.257]} rotation={[-Math.PI, 0.006, -Math.PI]} scale={3} />
      {/* Doors */}
      <mesh castShadow receiveShadow geometry={nodes.Mesh1034.geometry} material={nodes.Mesh1034.material} position={[-1.834, 0.179, -24.529]} scale={[1.14, 2, 1.1]} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh1067.geometry} material={nodes.Mesh1067.material} position={[-35.613, 0.179, -24.529]} scale={[1.14, 2, 1.1]} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh1082.geometry} material={nodes.Mesh1082.material} position={[-73.046, 0.179, -24.529]} scale={[1.14, 2, 1.1]} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh1084.geometry} material={nodes.Mesh1084.material} position={[-107.792, 0.179, -24.529]} scale={[1.14, 2, 1.1]} />
      {/* Side structures */}
      <mesh castShadow receiveShadow geometry={nodes.Mesh1071.geometry} material={nodes.Mesh1071.material} position={[-125.816, 3.712, -4.138]} rotation={[0, 1.466, 0]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh1073.geometry} material={nodes.Mesh1073.material} position={[-125.816, 3.712, -15.55]} rotation={[0, 1.466, 0]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh1079.geometry} material={nodes.Mesh1079.material} position={[-125.816, 3.712, 15.643]} rotation={[0, 1.466, 0]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh1080.geometry} material={nodes.Mesh1080.material} position={[-125.816, 3.712, 4.231]} rotation={[0, 1.466, 0]} scale={4} />
      {/* Repeated props (instanced for performance) */}
      <instancedMesh castShadow receiveShadow args={[nodes.Mesh1063.geometry, nodes.Mesh1063.material, 23]} instanceMatrix={nodes.Mesh1063.instanceMatrix} />
      <instancedMesh castShadow receiveShadow args={[nodes.Mesh1045.geometry, nodes.Mesh1045.material, 18]} instanceMatrix={nodes.Mesh1045.instanceMatrix} />
      <instancedMesh castShadow receiveShadow args={[nodes.Mesh1059.geometry, nodes.Mesh1059.material, 59]} instanceMatrix={nodes.Mesh1059.instanceMatrix} />
      <instancedMesh castShadow receiveShadow args={[nodes.Mesh1034_1.geometry, nodes.Mesh1034_1.material, 7]} instanceMatrix={nodes.Mesh1034_1.instanceMatrix} />
    </group>
  );
}

useGLTF.preload("/models/palhero-parts.glb");
