/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sign-only.glb --types
Source: public/models/sign-only.glb

The "sign" object, lifted out of the full sign.glb scene re-export (which also
carried a duplicate of the whole city). Only the sign mesh is kept, with its
transform reset to the origin so this component owns its own placement.

Like the truck GLBs, this mesh carries ONLY vertex positions + normals — no UVs,
no separate parts, no material — so we give it one solid white flat-shaded
material here. Flat shading keeps the crisp low-poly facets that match the rest
of the scene; the lighting rig still reads the form so it doesn't look like a
flat cut-out.
*/

"use client";

import * as THREE from "three";
import { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Sign: THREE.Mesh;
  };
  materials: Record<string, never>;
};

// ─── Sign finish (tunable) ───────────────────────────────────────────────────
const SIGN_COLOR = "#346BFF"; // accent blue
const ROUGHNESS = 0.55; // matte-ish; lower = glossier
const METALNESS = 0.0;

export function Sign(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/models/sign-only.glb") as unknown as GLTFResult;

  // Split every triangle into its own vertices so normals come out flat-faceted
  // (the low-poly look), matching the rest of the scene.
  const geometry = useMemo(() => {
    const geo = nodes.Sign.geometry.toNonIndexed();
    geo.computeVertexNormals();
    return geo;
  }, [nodes]);

  const material = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: SIGN_COLOR,
        flatShading: true,
        roughness: ROUGHNESS,
        metalness: METALNESS,
      }),
    []
  );

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={geometry} material={material} />
    </group>
  );
}

useGLTF.preload("/models/sign-only.glb");
