/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Track.glb --types
Source: public/models/Track.glb

A single merged mesh (the asphalt-paver truck). The GLB carries ONLY vertex
positions — no UVs, no separate parts, no material — so we can't bind an image
texture or pick out "the cabin". Instead the truck is painted procedurally in
buildTruckGeometry(): every triangle is tinted from where it sits on the body
(local Y height, with a Z-side check), which cleanly separates the low, side-
mounted crawler tracks from the tall central hopper. Result matches the
reference: a construction-yellow body riding on near-black tracks.
*/

"use client";

import * as THREE from "three";
import { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh10: THREE.Mesh;
  };
  materials: Record<string, never>;
};

// ─── Truck paint (tunable) ───────────────────────────────────────────────────
// Colours lifted from the reference render.
const BODY_COLOR = "#F2B233"; // construction amber-yellow (hopper / body / panels)
const CHASSIS_COLOR = "#3A3D42"; // dark charcoal (engine cover, front blade, screed)
const TRACK_COLOR = "#191A1C"; // near-black rubber crawler tracks

// Height bands as a fraction of the truck's total height (0 = bottom, 1 = top).
// Anything below TRACK_TOP is the undercarriage; between TRACK_TOP and
// CHASSIS_TOP is the dark chassis band; everything above is the yellow body.
const TRACK_TOP = 0.22; // bottom 22% of the height → crawler tracks
const CHASSIS_TOP = 0.4; // 22%–40% of the height → dark chassis / blade / screed

// Subtle hand-painted variation so the flat yellow isn't dead-flat (low-poly
// "texture"): each face's brightness is nudged a touch by a hash of its centre.
const BODY_JITTER = 0.06; // ± brightness applied to the body colour only

// Material finish — flat-shaded for crisp low-poly facets that read as cartoon.
const BODY_ROUGHNESS = 0.6;

// Deterministic 0..1 hash from a face centroid — keeps the jitter stable across
// renders (no flicker) while still looking randomly hand-painted.
function faceHash(x: number, y: number, z: number) {
  const s = Math.sin(x * 12.9898 + y * 78.233 + z * 37.719) * 43758.5453;
  return s - Math.floor(s);
}

// Paint the single truck mesh: split every triangle into its own vertices (so
// colours stay crisp at the seams and normals come out flat-faceted), then tint
// each face by height into tracks / chassis / body.
function buildTruckGeometry(source: THREE.BufferGeometry) {
  const geo = source.toNonIndexed();
  geo.computeVertexNormals(); // non-indexed → per-face flat normals (low-poly look)

  const pos = geo.getAttribute("position") as THREE.BufferAttribute;
  geo.computeBoundingBox();
  const bb = geo.boundingBox!;
  const minY = bb.min.y;
  const spanY = bb.max.y - bb.min.y || 1;
  const halfZ = Math.max(Math.abs(bb.min.z), Math.abs(bb.max.z)) || 1;

  const body = new THREE.Color(BODY_COLOR);
  const chassis = new THREE.Color(CHASSIS_COLOR);
  const track = new THREE.Color(TRACK_COLOR);
  const tmp = new THREE.Color();

  const colors = new Float32Array(pos.count * 3);
  const faceCount = pos.count / 3;

  for (let f = 0; f < faceCount; f++) {
    const a = f * 3;
    // face centroid
    const cx = (pos.getX(a) + pos.getX(a + 1) + pos.getX(a + 2)) / 3;
    const cy = (pos.getY(a) + pos.getY(a + 1) + pos.getY(a + 2)) / 3;
    const cz = (pos.getZ(a) + pos.getZ(a + 1) + pos.getZ(a + 2)) / 3;

    const h = (cy - minY) / spanY; // 0 at the bottom, 1 at the top
    const sideways = Math.abs(cz) / halfZ; // 0 at the centreline, 1 at the edges

    if (h < TRACK_TOP) {
      // low + out toward the sides = crawler track; low + central = dark chassis
      tmp.copy(sideways > 0.45 ? track : chassis);
    } else if (h < CHASSIS_TOP) {
      tmp.copy(chassis);
    } else {
      // yellow body, nudged per-face for a hand-painted matte finish
      const j = (faceHash(cx, cy, cz) - 0.5) * 2 * BODY_JITTER;
      tmp.copy(body).offsetHSL(0, 0, j);
    }

    for (let v = 0; v < 3; v++) {
      const i = (a + v) * 3;
      colors[i] = tmp.r;
      colors[i + 1] = tmp.g;
      colors[i + 2] = tmp.b;
    }
  }

  geo.setAttribute("color", new THREE.BufferAttribute(colors, 3));
  return geo;
}

export function Track(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/models/Track.glb") as unknown as GLTFResult;

  const geometry = useMemo(
    () => buildTruckGeometry(nodes.Mesh10.geometry),
    [nodes]
  );

  // One flat-shaded material; all the colour comes from the per-face vertex
  // colours baked above (yellow body, charcoal chassis, near-black tracks).
  const material = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        vertexColors: true,
        flatShading: true,
        roughness: BODY_ROUGHNESS,
        metalness: 0.05,
      }),
    []
  );

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={geometry} material={material} />
    </group>
  );
}

useGLTF.preload("/models/Track.glb");
