/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Truck-v2.glb --types
Source: public/models/Truck-v2.glb

Same single merged mesh (the asphalt-paver truck) as Track.glb, just a revised
export. The GLB still carries ONLY vertex positions — no UVs, no separate parts,
no material — so we paint it procedurally in buildTruckGeometry(): every
triangle is tinted from where it sits on the body (local Y height, with a Z-side
check), which cleanly separates the low, side-mounted crawler tracks from the
tall central hopper. Truck-v2 shares Track.glb's size/orientation (bbox
~1.9 x 0.9 x 1.6, centred at origin), so it drops in at the same size, position
and direction with the exact same transform props.
*/

"use client";

import * as THREE from "three";
import { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh10: THREE.Mesh;
  };
  materials: Record<string, never>;
};

// ─── Truck paint (tunable) ───────────────────────────────────────────────────
// Colours sampled from the premium reference render — a warm golden construction
// amber over charcoal panels and near-black rubber crawler tracks.
const BODY_COLOR = "#F0A92A"; // warm construction amber (hopper / body / panels)
const CHASSIS_COLOR = "#36393F"; // dark charcoal (engine cover, front blade, screed)
const TRACK_COLOR = "#171819"; // near-black rubber crawler tracks
const CAB_COLOR = "#1A1B1D"; // black operator cab — seats, control screens
const EXHAUST_COLOR = "#8C9095"; // grey steel — exhaust pipe & beacon post on top

// Height bands as a fraction of the truck's total height (0 = bottom, 1 = top).
// Mapped from the model's own geometry (a vertical slice analysis of the merged
// mesh): tracks/chassis at the base, the amber body in the middle, the dark cab
// cluster above it, then the thin exhaust/beacon posts at the very top.
const TRACK_TOP = 0.22; // bottom 22% → crawler tracks (sides) / dark chassis (centre)
const CHASSIS_TOP = 0.4; // 22%–40% → dark chassis / front blade / screed
const CAB_BOTTOM = 0.62; // 40%–62% → amber hopper & body panels
const EXHAUST_BOTTOM = 0.8; // 62%–80% → black cab (seats/screens); above → grey exhaust

// ── Premium depth shading (baked fake ambient occlusion) ─────────────────────
// A product render reads as "premium" mostly because of soft occlusion in the
// crevices and a gentle top-down light gradient. This GLB has no UVs and no AO
// map, so we bake both straight into the vertex colours — the model gains real
// depth instead of looking like flat poster paint.
const AO_GRADIENT = 0.16; // bottom of the truck is this much darker than the top
const AO_UNDERSIDE = 0.24; // extra darkening on downward-facing faces (contact shade)
const TOP_SHEEN = 0.06; // faint brighten on up-facing body panels (catches the sky)

// Subtle hand-painted variation so the flat yellow isn't dead-flat (low-poly
// "texture"): each face's brightness is nudged a touch by a hash of its centre.
// Kept low — premium reads as clean, not noisy.
const BODY_JITTER = 0.025; // ± brightness applied to the body colour only

// Material finish — flat-shaded for crisp low-poly facets that read as cartoon,
// with a satin clearcoat sheen (see the material below) for that glossy render look.
const BODY_ROUGHNESS = 0.45;

// Deterministic 0..1 hash from a face centroid — keeps the jitter stable across
// renders (no flicker) while still looking randomly hand-painted.
function faceHash(x: number, y: number, z: number) {
  const s = Math.sin(x * 12.9898 + y * 78.233 + z * 37.719) * 43758.5453;
  return s - Math.floor(s);
}

// Paint the single truck mesh: split every triangle into its own vertices (so
// colours stay crisp at the seams and normals come out flat-faceted), then tint
// each face by height into tracks / chassis / body.
function buildTruckGeometry(source: THREE.BufferGeometry) {
  const geo = source.toNonIndexed();
  geo.computeVertexNormals(); // non-indexed → per-face flat normals (low-poly look)

  const pos = geo.getAttribute("position") as THREE.BufferAttribute;
  const nor = geo.getAttribute("normal") as THREE.BufferAttribute;
  geo.computeBoundingBox();
  const bb = geo.boundingBox!;
  const minY = bb.min.y;
  const spanY = bb.max.y - bb.min.y || 1;
  const halfZ = Math.max(Math.abs(bb.min.z), Math.abs(bb.max.z)) || 1;

  const body = new THREE.Color(BODY_COLOR);
  const chassis = new THREE.Color(CHASSIS_COLOR);
  const track = new THREE.Color(TRACK_COLOR);
  const cab = new THREE.Color(CAB_COLOR);
  const exhaust = new THREE.Color(EXHAUST_COLOR);
  const tmp = new THREE.Color();

  const colors = new Float32Array(pos.count * 3);
  const faceCount = pos.count / 3;

  for (let f = 0; f < faceCount; f++) {
    const a = f * 3;
    // face centroid
    const cx = (pos.getX(a) + pos.getX(a + 1) + pos.getX(a + 2)) / 3;
    const cy = (pos.getY(a) + pos.getY(a + 1) + pos.getY(a + 2)) / 3;
    const cz = (pos.getZ(a) + pos.getZ(a + 1) + pos.getZ(a + 2)) / 3;

    const h = (cy - minY) / spanY; // 0 at the bottom, 1 at the top
    const sideways = Math.abs(cz) / halfZ; // 0 at the centreline, 1 at the edges
    const ny = nor.getY(a); // face normal Y (flat-shaded → one normal per face)

    let isBody = false;
    if (h < TRACK_TOP) {
      // low + out toward the sides = crawler track; low + central = dark chassis
      tmp.copy(sideways > 0.45 ? track : chassis);
    } else if (h < CHASSIS_TOP) {
      tmp.copy(chassis);
    } else if (h < CAB_BOTTOM) {
      // amber hopper & side body panels
      tmp.copy(body);
      isBody = true;
    } else if (h < EXHAUST_BOTTOM) {
      // operator cab cluster on top — seats & control screens (black)
      tmp.copy(cab);
    } else {
      // thin posts at the very top — exhaust pipe & beacon stack (grey)
      tmp.copy(exhaust);
    }

    // ── Bake the premium depth shading into the face colour ──────────────────
    // 1) a soft vertical gradient (sky-lit top, shaded base),
    // 2) a contact-shade on downward-facing faces (fake AO in the crevices),
    // 3) body only: a faint sky-catch sheen on up-facing panels + the
    //    hand-painted per-face jitter so the amber isn't dead-flat.
    let light = (h - 0.5) * AO_GRADIENT;
    if (ny < 0) light -= AO_UNDERSIDE * -ny;
    if (isBody) {
      if (ny > 0) light += TOP_SHEEN * ny;
      light += (faceHash(cx, cy, cz) - 0.5) * 2 * BODY_JITTER;
    }
    tmp.offsetHSL(0, 0, light);

    for (let v = 0; v < 3; v++) {
      const i = (a + v) * 3;
      colors[i] = tmp.r;
      colors[i + 1] = tmp.g;
      colors[i + 2] = tmp.b;
    }
  }

  geo.setAttribute("color", new THREE.BufferAttribute(colors, 3));
  return geo;
}

export function TruckV2(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/models/Truck-v2.glb") as unknown as GLTFResult;

  const geometry = useMemo(
    () => buildTruckGeometry(nodes.Mesh10.geometry),
    [nodes]
  );

  // One flat-shaded material; all the colour comes from the per-face vertex
  // colours baked above (amber body, charcoal chassis, near-black tracks). A
  // light clearcoat lays a satin sheen over everything so the truck catches the
  // studio environment the way the reference render does — the "premium" pop.
  const material = useMemo(
    () =>
      new THREE.MeshPhysicalMaterial({
        vertexColors: true,
        flatShading: true,
        roughness: BODY_ROUGHNESS,
        metalness: 0.0,
        clearcoat: 0.6,
        clearcoatRoughness: 0.35,
        envMapIntensity: 0.9,
      }),
    []
  );

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={geometry} material={material} />
    </group>
  );
}

useGLTF.preload("/models/Truck-v2.glb");
